// Automatically generated by astro-icon
// b10d82a64cbcc56ff1bd7629551d683c9f7516cd57896139992b9d9f04e3af75

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right-up-line"
		| "astro_dark"
		| "Astro_light"
		| "github-fill"
		| "group-fill"
		| "instagram-fill"
		| "link"
		| "logo"
		| "message-2-fill"
		| "mongodb"
		| "nextjs_icon_dark"
		| "nodejs"
		| "react"
		| "tiktok-fill"
		| "time-fill"
		| "time-line"
		| "tools-fill"
		| "twitter-x-fill"
		| "typescript"
		| "youtube-fill";
}