// Automatically generated by astro-icon
// 79090c14b281af6ee7c51ec7c7fdea9f0259ac9bac901c10dfca771b85051ee7

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right-up-line"
		| "astro_dark"
		| "Astro_light"
		| "github-fill"
		| "group-fill"
		| "instagram-fill"
		| "link"
		| "linkedin"
		| "logo"
		| "message-2-fill"
		| "mongodb"
		| "nextjs_icon_dark"
		| "nodejs"
		| "react"
		| "tiktok-fill"
		| "time-fill"
		| "time-line"
		| "tools-fill"
		| "twitter-x-fill"
		| "typescript"
		| "youtube-fill";
}